name: Docker Build

on:
  push: # 每当有代码push到仓库时触发
    branches:
      - main # 修改为你希望触发构建的分支，如 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub (或其他镜像仓库)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # 存储在GitHub仓库的Secrets中
        password: ${{ secrets.DOCKERHUB_TOKEN }} # 存储在GitHub仓库的Secrets中

    - name: Build Docker image
      run: docker build -t taohuajiu/onebot:latest .
      # 替换为你的Docker Hub用户名和镜像名称，latest是标签

    - name: Push Docker image
      run: docker push taohuajiu/onebot:latest
      # 替换为你的Docker Hub用户名和镜像名称，latest是标签


